# Generated by Django 5.0 on 2024-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groqkey',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='pdf_documents/'),
        ),
    ]
